### ISSUE TITLE
Ask

### ISSUE THREAD

**Issue by IsnaniWidhiHidayat** [Ourpalm/ILRuntime#266]
Hey dev, for a long time I am searching plugin like this. But is just for Mono script backend unity or can use IL2CPP backend?  I just download your unity demo but if I build with IL2CPP got lot error.
![Error](https://user-images.githubusercontent.com/28438667/54479579-5b7f7380-47db-11e9-8216-c08bbe18b7cb.png)

**Comment by liiir1985** [comment]
This project is explicitly made for iOS, for mono backend you won't need this at all, you can load dll directly through Assembly.Load API.
The error you got is due to bugs of unity, I already reported and the bugs are confirmed by Unity. This only occurs for Unity 2018.3 and later(with Rosyln compiler). You can use the latest version from master branch of the main repo, which contains a workaround for this issue. But you'll need some modification of the demo in order to use the latest version, and it's not yet documented.
